name: Delphi Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Delphi environment
        run: |
          echo "Setting up Delphi environment"
          $env:Path += ";C:\Program Files (x86)\Embarcadero\Studio\23.0\bin"
          echo $env:Path

      - name: Build Delphi Project (64-bit)
        run: |
          dcc64.exe .\ServerAPI.dpr -B -E.\Output -Q
        continue-on-error: false

      - name: Verify build output
        run: |
          dir .\Output

      - name: Push changes to GitHub
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated build and push from GitHub Actions"
          git push
